### ISSUE TITLE
Problema de Instalação

### ISSUE THREAD

**Issue by samuruiz** [niobio-cash/Downloads#2]
Ola, estou tentando instalar este arquivo da niobio-cash, e esta dando erro, ja desativei meu antivirus e tudo mais, mas mesmo assim esta dando erro.

**Comment by BrazilianGirl** [comment]
The macOS wallet has a problem on opening it keeps freezing.
Alguns dias funcionou perfeitamente e agora não esta abrindo.

**Comment by gchernichenco** [comment]
Olá. Você conseguiu abrir a wallet no Mac? A minha também esta dando problema.

**Comment by gchernichenco** [comment]
Olá @BrazilianGirl. Você conseguiu abrir a wallet no Mac? A minha também esta dando problema.

**Comment by samuruiz** [comment]
O meu é windows, eu não consegui.

Em 27 de fev de 2018 12:22 PM, "gchernichenco" <notifications@github.com>
escreveu:

**Comment by wellfelix** [comment]
Para quem usa windows e esta dando erro basta entrar no link abaixo e baixar a biblioteca de dll.
http://www.teteututors.tech/erro-api-ms-win-crt-runtime-l1-1-0-dll-windows-7-8-1-e-10/

**Comment by FredericoVillani** [comment]
Atualizem para a versão 1.3.1 em https://github.com/niobio-cash/niobio-wallet/releases
Qualquer dúvida, abram issue lá por favor.
