### ISSUE TITLE
Wallet não abre no Mac

### ISSUE THREAD

**Issue by gchernichenco** [niobio-cash/Downloads#3]
Minha wallet funcionava normalmente no Mac, mas depois começou a fechar sozinha e agora nem abre mais, aparece que está carregando a blockchain e fecha. Já baixei a blockchain e descompactei na pasta e continua sem funcionar. Alguém pode me ajudar?

**Comment by helder-garcia** [comment]
Por favor, poste aqui o conteúdo do arquivo ~/.niobio/niobiowallet.cfg

**Comment by Elion117** [comment]
Estou tendo EXATAMENTE O MESMO PROBLEMA aqui, porém com Win10 x64

**Comment by FredericoVillani** [comment]
Atualizem para a versão 1.3.1 em https://github.com/niobio-cash/niobio-wallet/releases
Qualquer dúvida, abram issue lá por favor.
