### ISSUE TITLE
ola sua Wallet Gui 1.2.3 nao abre windows 7 32 bits

### ISSUE THREAD

**Issue by marceloz6** [niobio-cash/Downloads#6]
ola sua Wallet Gui 1.2.3 não esta abrindo no meu windows 7 32 bits tem como arrumar da erro Vcruntime140ddl esse aquivo nao pode ser aberto pelo windows

**Comment by stttt1** [comment]
Aqui também não abre no meu Windows 10 pro 32bit. a versão nova 1.2.3.. cpu core 2 duo. 3GB ram.

então só abre a versão antiga do programa. 1.2.2!!

tinha deixado sincronizando e não terminou, passou 8 horas e não baixou tudo da sincronização...
então fechei abri denovo... depois baixei o blockchain do 1.2.2 pra ver se melhora e ainda ta sincronizando e não recebi as moedas que comprei... internet aqui Net 10MB.

poderiam colocar opção de abrir carteira pelo site, ver saldo, com e-mail pra ficar mais seguro e rápido, depois ter opção de vincular ao e-mail. e melhorar o app, quando estiver minerando exemplo a cada 30 minutos aparecer, você minerou x moedas e ganhou x.

aguardo atualização

**Comment by marceloz6** [comment]
e brincadeira ate hoje nao arrumaram esse erro versão windows 7 32 bits para windos dando mesmo erro, nem nova versão que lancaram nao abre pasciencia

**Comment by stttt1** [comment]
to aguardando atualização deles também e versão web da Wallet.... pois a nova versão não abre em windows 10 pro 32bits (x86).. pensei que era o Visual c++ o erro, mas não é! eu baixei no site da Microsoft e atualizei e não resolveu.

**Comment by marceloz6** [comment]
Eu achei esta wallet niobio cash 1.2.2 32 bits basta você instalar ela e baixar a BlockChain.11-04-2018.22-26.zip descompactar e digitar no menu do windons %appdata% e e subistituir os aquivos da BlockChain velha pela nova ai so esperar sincronizar aqui link de download da wallet 1.2.2 32 bits https://goo.gl/bPcYjs

TUTORIAL NO YOUTUBE
https://www.youtube.com/watch?v=rA5CMZL0_OU&vl=pt

**Comment by FredericoVillani** [comment]
Atualizem para a versão 1.3.1 em https://github.com/niobio-cash/niobio-wallet/releases
Qualquer dúvida, abram issue lá por favor.
