### ISSUE TITLE
Erro nova versão 1.2.3 não abre Windows 10 pro 32bit, 1.2.2 demora sincronizar

### ISSUE THREAD

**Issue by stttt1** [niobio-cash/Downloads#7]
essa versão nova não abre, então to usando a versão 1.2.2

porém demora muito pra sincronizar, deixei umas 8 horas  e não terminou, baixei o blockchain pra ver se melhora, mas ainda ta sincronizando e não caiu as moedas que comprei.
 poderiam melhorar o servidor e permitir criar e ver Carteira, saldo pelo site de vocês da niobio e depois fazer o app pra android.

meu pc Windows 10 pro 32bits (x86), 3GB ram, cpu core 2 duo, 160GB hd.

**Comment by FredericoVillani** [comment]
Atualize para a versão 1.3.1 em https://github.com/niobio-cash/niobio-wallet/releases
Qualquer dúvida, abram issue lá por favor.
