### ISSUE TITLE
erro 1.3.0 - windows 10 pro - 32bits

### ISSUE THREAD

**Issue by stttt1** [niobio-cash/Downloads#8]
Ola, eu baixei o arquivo, executei e aparece essa mensagem de erro.
![erro-niobio-cash-1 3 0 win32bits](https://user-images.githubusercontent.com/37893530/38474371-661d7248-3b74-11e8-972c-96e8becfd3a0.jpeg)

meu pc windows 10 pro 32bits, 3GB ram, cpu core 2 duo, esta tudo atualizado aqui.
aparece erro da foto e erro "vc runtime.." também

como posso resolver? estou baixando block chain..

**Comment by FredericoVillani** [comment]
Atualize para a versão 1.3.1 em https://github.com/niobio-cash/niobio-wallet/releases
Qualquer dúvida, abram issue lá por favor.
